//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProductividadCIISA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlProductividadCIISAEntities : DbContext
    {
        public ControlProductividadCIISAEntities()
            : base("name=ControlProductividadCIISAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Area> tbl_Area { get; set; }
        public virtual DbSet<tbl_Estado_peticion> tbl_Estado_peticion { get; set; }
        public virtual DbSet<tbl_Origen> tbl_Origen { get; set; }
        public virtual DbSet<tbl_Peticion> tbl_Peticion { get; set; }
        public virtual DbSet<tbl_Proyectos> tbl_Proyectos { get; set; }
        public virtual DbSet<tbl_Rol> tbl_Rol { get; set; }
        public virtual DbSet<tbl_Usuario> tbl_Usuario { get; set; }
        public virtual DbSet<tbl_LogFecha> tbl_LogFecha { get; set; }
        public virtual DbSet<tbl_Peticion_usuario> tbl_Peticion_usuario { get; set; }
    }
}
