//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProductividadCIISA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Peticion_usuario
    {
        public int id_peticion { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_final { get; set; }
    
        public virtual tbl_Peticion tbl_Peticion { get; set; }
        public virtual tbl_Usuario tbl_Usuario { get; set; }
    }
}
