//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProductividadCIISA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estado_peticion
    {
        public int id { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Descripcion_estado { get; set; }
        public Nullable<int> id_peticion { get; set; }
    
        public virtual tbl_Peticion tbl_Peticion { get; set; }
    }
}
